vim.g.mapleader = " "

-- Window Management
vim.keymap.set("n", "<C-\\>", "<C-w>v<C-w>l")
vim.keymap.set("n", "<C-h>", "<C-w>h")
vim.keymap.set("n", "<C-j>", "<C-w>j")
vim.keymap.set("n", "<C-k>", "<C-w>k")
vim.keymap.set("n", "<C-l>", "<C-w>l")
vim.keymap.set("n", "<leader>c", function()
	local current_file = vim.fn.expand("%:t:r")
	vim.fn.setreg("+", current_file)
	vim.fn.setreg('"', current_file)
end, { desc = "Copy [c]urrent filename without path and one extension removed" })
vim.keymap.set("n", "<leader>C", function()
	local current_file = vim.fn.expand("%")
	vim.fn.setreg("+", current_file)
	vim.fn.setreg('"', current_file)
end, { desc = "Copy [C]urrent filename with path" })
-- Buffer
vim.keymap.set("n", "<leader>x", function()
	vim.cmd("bp|bd #")
end, { silent = true })
vim.keymap.set("n", "<leader>X", function()
	vim.cmd("bd!")
end, {})
vim.keymap.set({ "n", "v" }, "<leader>y", [["+y]])
vim.keymap.set("n", "<leader>Y", [["+Y]])
vim.keymap.set("n", "<leader>o", ":update<CR>:source<CR>", { desc = "source updated nvim config" })
